version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:8080" # Map port 8080 of the container to 8080 on the host
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:80" # Map port 80 of the container to 3000 on the host
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
