name: Backend CI

on:
  push:
    branches:
      - backend
  pull_request:
    branches:
      - backend
      - dev

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Go environment
      - name: Set up Go environment
        uses: actions/setup-go@v3
        with:
          go-version: '1.23.3'

      # Change to backend directory
      - name: Change directory to backend
        run: cd backend

      # Install dependencies (go mod tidy)
      - name: Install Go dependencies
        run: |
          cd backend
          go mod tidy

      # Install GolangCI Lint
      - name: Install GolangCI Lint
        run: |
          cd backend
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      # Run GolangCI Lint
      - name: Run GolangCI Lint
        run: |
          cd backend
          golangci-lint run

      # Run tests
      - name: Run Tests
        run: |
          cd backend
          go test ./...

      # Build Docker image
      - name: Build Docker image
        run: |
          cd backend
          docker build -t backend .

      # Run Docker container
      - name: Run Docker container
        run: |
          cd backend
          docker run -d -p 8080:8080 backend
